name: BW1058_Ranked
version: '${project.version}'
main: br.com.pulse.bw1058_ranked.Main
commands:
  joinqueue:
    description: Entrar em uma fila
    aliases: [joinfila, entrarfila]
  leavequeue:
    description: Sair de uma fila
    aliases: [leavefila, sairfila]
  elo:
    description: Sobre elo
  rank:
    description: Ver rank
    aliases: [ranqueamento]